### ISSUE TITLE
Connect to a heart-rate sensor that is already connected to other app

### ISSUE THREAD

**Issue by georgbachmann** [mjordan56/HeartRateMonitor#1]
Hello,
I was having problems with my own heart-rate monitor and so I stumbled upon yours. I was wondering if you know if it's possible to somehow connect to a heart-rate sensor while an other app is also connected to it? I am wondering because if I start my own app first I can connect perfectly, also when I start f.e. Strava afterwards, it can also connect just fine. But if I do it the other way around, start Strava first and then my own app, I can't find any sensors any more.

Do you know the trick Strava and others are doing?

Cheers,
Georg

**Comment by mjordan56** [comment]
Hi Georg,

It's been a while since I've visited this code so take my response appropriately. The Polar heart rate sensor is a Bluetooth LE (or Bluetooth Smart) device. BLE devices like this tend to broadcast their advertising packets while they are not connected to a BLE client. Once a BLE client has requested to connect to the BLE peripheral, such as the Polar sensor, the peripheral stops advertising and communicates exclusively with the client. Once the peripheral disconnects from a client it becomes available to other clients.

So, to answer your question, I'm not sure why the Strava is able to connect to your heart rate device after your app is connected. You might consider getting a Bluetooth sniffer like the Bluefruit LE Sniffer from Adafruit. This is a fairly cheap BLE sniffer and will let you see the BLE packet data from the heart rate sensor.

Good luck in resolving your problem.

Michael
